### ISSUE TITLE
I meet an error when I use dataset_process.py

### ISSUE THREAD

**Issue by huhuhuhuha** [ravikothari510/crossattention_radar_detector#1]
/crossattention_radar_detector$ python dataset_process.py --gt_path 'gt_anno.json'  --carrada_dir 'data/Carrada' --raw_carrada 'data/Carrada_RAD' 
  0%|                                                                                | 0/30 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/raid/crossattention_radar_detector/dataset_process.py", line 86, in <module>
    main()
  File "/raid/crossattention_radar_detector/dataset_process.py", line 73, in main
    ad_map[i, ::] = get_admap(rad_file_path=rad_file_path)
ValueError: could not broadcast input array from shape (64,256) into shape (256,64)

**Comment by ravikothari510** [comment]
Hi,
I have updated the script, initialized the ad array with the correct dimensions.

**Comment by ravikothari510** [comment]
Done
