### ISSUE TITLE
One question about computing the ad instead of directly using 

### ISSUE THREAD

**Issue by kathy-lee** [ravikothari510/crossattention_radar_detector#2]
Hi @ravikothari510 , thank you for sharing the code of your paper with us! I just have two questions not an issue: 
1. Is there any consideration that you compute the ad (`get_admap(rad_file_path)`) instead of using the existing ad (in `angle_doppler_processed` and `angle_doppler_raw`) from the raw CARRADA dataset? 
2. How is the process of creating updated annotations `gt_anno.json`? I could not find how it be created in the project
Thank you in advance!

**Comment by ravikothari510** [comment]
Hi @kathy-lee, sorry for the late reply. Thanks for taking interest in our work. 

1. The CARRADA dataset provides 3D FFT maps for angle/doppler channels, I experimented with the compressed original data but it wasn't effective in VRU's detection . Hence, I transformed the 3D  FFT to raw data (via inverse FFT), then compressed it to single channel and removed DC component (it's a constant peak along the middle of the 2D FFT). And I wanted more control over how 2D FFT maps are generated hence we transformed the raw data again.
2
3. gt_anno.json is an updated annotation. It was generated by optimizing trajectory splines and manually updating image annotation and later project them on radar frame. I do not have a script for this, it's just grunt work.
